on:
  push:
    branches:
      - master



jobs:
  build:
    run-on: ubunto-latest

    steps:
      - name: "Testing Github action"
        run: pwd

      - name: "Testing Printing"
        run: echo Ahmed